In [1]:
# import libraries
import os
import pandas as pd
from cryptography.fernet import Fernet

In [2]:
# opwn the file key
with open('filekey.key', 'rb') as f:
  key = f.read()

In [3]:
# store key in the fernet variable
fernet = Fernet(key)

In [4]:
# open the file
with open('trends_mart.csv', 'rb') as f:
  data = f.read()

In [5]:
# Decrypt
decryption = fernet.decrypt(data)

In [6]:
# overwrite the data with decryption
with open('trends_mart.csv', 'wb') as f:
  f.write(decryption)

In [7]:
# Explore the data
trends_mart = pd.read_csv('trends_mart.csv')
trends_mart.head()

,Customer_ID,Goals and Aspirations,Pain Points and Challenges,Interest and Hobbies,Lifestyle and Values,Decision Making triggers,Name,Age,Gender,Location,...,Online Purchase Frequency,Offline Purchase Frequency,Communication Preference,Technology Usage,Average Order Value,NPS Score,Customer Lifespan Years,Marketing Spend,Total Purchases,Revenue Generated
0,CUST1,Travel the world,Limited access to services,Sports,Community-driven,Discounts and offers,Aarav Sharma,34,Male,Rural,...,1,8,Social,Low,874,6,3.3,14362,9,7866
1,CUST2,Travel the world,Lack of career opportunities,Cooking,Environmentally conscious,Social media influence,Shreya Sen,53,Female,Urban,...,6,2,Phone,Low,3861,3,1.3,37194,50,193050
2,CUST3,Start a business,Health issues,Fitness,Career-focused,Brand reputation,Suresh Nair,44,Male,Rural,...,1,6,Social,High,737,3,3.4,10676,14,10318
3,CUST4,Better health and fitness,High living costs,Fitness,Community-driven,Social media influence,Shreya Sen,20,Female,Rural,...,3,9,Email,Medium,3852,9,5.9,39210,14,53928
4,CUST5,Education advancement,Technology barriers,Sports,Adventurous,Discounts and offers,Neha Bhatia,43,Female,Rural,...,2,3,Phone,Low,3626,4,7.2,48542,17,61642

In [8]:
# shape
trends_mart.shape

(100, 26)

In [9]:
# data types
trends_mart.dtypes

Customer_ID                    object
Goals and Aspirations          object
Pain Points and Challenges     object
Interest and Hobbies           object
Lifestyle and Values           object
Decision Making triggers       object
Name                           object
Age                             int64
Gender                         object
Location                       object
Education Level                object
Occupation                     object
Annual Income                   int64
Marital Status                 object
Product Name                   object
Product Line                   object
Online Purchase Frequency       int64
Offline Purchase Frequency      int64
Communication Preference       object
Technology Usage               object
Average Order Value             int64
NPS Score                       int64
Customer Lifespan Years       float64
Marketing Spend                 int64
Total Purchases                 int64
Revenue Generated               int64
dtype: object

In [10]:
# missing values
trends_mart.isnull().sum()

Customer_ID                   0
Goals and Aspirations         0
Pain Points and Challenges    0
Interest and Hobbies          0
Lifestyle and Values          0
Decision Making triggers      0
Name                          0
Age                           0
Gender                        0
Location                      0
Education Level               0
Occupation                    0
Annual Income                 0
Marital Status                0
Product Name                  0
Product Line                  0
Online Purchase Frequency     0
Offline Purchase Frequency    0
Communication Preference      0
Technology Usage              0
Average Order Value           0
NPS Score                     0
Customer Lifespan Years       0
Marketing Spend               0
Total Purchases               0
Revenue Generated             0
dtype: int64

In [11]:
# Column names
trends_mart.columns

Index(['Customer_ID', 'Goals and Aspirations', 'Pain Points and Challenges',
       'Interest and Hobbies', 'Lifestyle and Values',
       'Decision Making triggers', 'Name', 'Age', 'Gender', 'Location',
       'Education Level', 'Occupation', 'Annual Income', 'Marital Status',
       'Product Name', 'Product Line', 'Online Purchase Frequency',
       'Offline Purchase Frequency', 'Communication Preference',
       'Technology Usage', 'Average Order Value', 'NPS Score',
       'Customer Lifespan Years', 'Marketing Spend', 'Total Purchases',
       'Revenue Generated'],
      dtype='object')

In [12]:
# Group customers by Location (Urban/Rural) and find the average Annual Income.
trends_mart.groupby('Location')['Annual Income'].mean().round(2)

Location
Rural    816891.55
Urban    823686.57
Name: Annual Income, dtype: float64

In [15]:
# Find the most common Communication Preference for Urban customers.
trends_mart[trends_mart['Location'] == 'Urban']['Communication Preference'].mode()

0    Social
Name: Communication Preference, dtype: object

In [16]:
# Group customers by Technology Usage and calculate the average Online Purchase Frequency.
trends_mart.groupby('Technology Usage')['Online Purchase Frequency'].mean().round(2)

Technology Usage
High      5.81
Low       4.91
Medium    4.72
Name: Online Purchase Frequency, dtype: float64

In [20]:
# Find the number of customers whose Goals and Aspirations is "Better health and fitness".
trends_mart[(trends_mart['Goals and Aspirations'] == 'Better health and fitness')]['Customer_ID'].count()

np.int64(20)

In [22]:
# Group customers by Lifestyle and values and find the average Annual Income.
trends_mart.groupby(['Lifestyle and Values'])['Annual Income'].mean().round(2)

Lifestyle and Values
Adventurous                  1055580.90
Career-focused                834057.12
Community-driven              831429.68
Environmentally conscious     757094.30
Family-oriented               713779.55
Luxury-seeking                642763.58
Minimalist                    718262.00
Name: Annual Income, dtype: float64

In [24]:
# Find the most common Decision-Making trigger for customers with High Technology Usage.
trends_mart[trends_mart['Technology Usage'] == 'High']['Decision Making triggers'].mode()

0    Social media influence
Name: Decision Making triggers, dtype: object